In [1]:
import numpy as np # linear algebra
import pandas as pd
import sqlite3

df_olist_customers = pd.read_csv('/olist_customers_dataset.csv')
df_olist_sellers = pd.read_csv('/olist_sellers_dataset.csv')
df_olist_order_reviews= pd.read_csv('/olist_order_reviews_dataset.csv')
df_olist_order_items= pd.read_csv('/olist_order_items_dataset.csv')
df_olist_products= pd.read_csv('/olist_products_dataset.csv')
df_olist_geolocation= pd.read_csv('/olist_geolocation_dataset.csv')
df_product_category_name_translation= pd.read_csv('/product_category_name_translation.csv')
df_olist_orders = pd.read_csv('/olist_orders_dataset.csv')
df_olist_order_payments= pd.read_csv('/olist_order_payments_dataset.csv')

df_olist_customers.head()

from sqlalchemy import create_engine
engine = create_engine('sqlite://', echo=False)

# export the dataframe as a table 'playstore' to the sqlite engine
df_olist_customers.to_sql("olist_customers", con =engine)
df_olist_sellers.to_sql("olist_sellers", con =engine)
df_olist_order_reviews.to_sql("olist_order_reviews", con =engine)
df_olist_order_items.to_sql("olist_order_items", con =engine)
df_olist_products.to_sql("olist_products_dataset", con =engine)
df_olist_geolocation.to_sql("olist_geolocation", con =engine)
df_product_category_name_translation.to_sql("product_category_name_translation", con =engine)
df_olist_orders.to_sql("olist_orders", con =engine)
df_olist_order_payments.to_sql("olist_order_payments", con =engine)
df_olist_order_payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [2]:
sql='''

Select * from olist_customers
limit 5


''';


df_sql = pd.read_sql_query(sql,con=engine)
df_sql.head()

,index,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

2. Create SQLite Database and Export DataFrames.

Create a SQLite database using SQLAlchemy.
Export each dataframe as a table to the SQLite database.

In [3]:
engine = create_engine('sqlite:///e_comerce.db', echo=False)
df_olist_customers.to_sql("olist_customers", con =engine)
df_olist_sellers.to_sql("olist_sellers", con =engine)
df_olist_order_reviews.to_sql("olist_order_reviews", con =engine)
df_olist_order_items.to_sql("olist_order_items", con =engine)
df_olist_products.to_sql("olist_products_dataset", con =engine)
df_olist_geolocation.to_sql("olist_geolocation", con =engine)
df_product_category_name_translation.to_sql("product_category_name_translation", con =engine)
df_olist_orders.to_sql("olist_orders", con =engine)
df_olist_order_payments.to_sql("olist_order_payments", con =engine)
df_olist_order_payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [4]:
for table in ['olist_customers','olist_sellers','olist_order_reviews','olist_order_items','olist_products_dataset','olist_geolocation','product_category_name_translation','olist_orders','olist_order_payments']:
    col =pd.read_sql(f"SELECT * FROM {table} LIMIT 0",engine).columns.tolist()
    col2 =pd.read_sql(f"SELECT * FROM {table} ",engine).info()
    print(f'{table} : {col2}\n')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   index                     99441 non-null  int64
 1   customer_id               99441 non-null  object
 2   customer_unique_id        99441 non-null  object
 3   customer_zip_code_prefix  99441 non-null  int64
 4   customer_city             99441 non-null  object
 5   customer_state            99441 non-null  object
dtypes: int64(2), object(4)
memory usage: 4.6+ MB
olist_customers : None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   index                   3095 non-null   int64
 1   seller_id               3095 non-null   object
 2   seller_zip_code_prefix  3095 non-null   int64
 3   seller_city             3095 non-null   object
 4   seller_state            3095 non-null   object
dtypes: int64(2), object(3)
memory usage: 121.0+ KB
olist_sellers : None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   index                    99224 non-null  int64
 1   review_id                99224 non-null  object
 2   order_id                 99224 non-null  object
 3   review_score             99224 non-null  int64
 4   review_comment_title     11568 non-null  object
 5   review_comment_message   40977 non-null  object
 6   review_creation_date     99224 non-null  object
 7   review_answer_timestamp  99224 non-null  object
dtypes: int64(2), object(6)
memory usage: 6.1+ MB
olist_order_reviews : None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   index                112650 non-null  int64
 1   order_id             112650 non-null  object
 2   order_item_id        112650 non-null  int64
 3   product_id           112650 non-null  object
 4   seller_id            112650 non-null  object
 5   shipping_limit_date  112650 non-null  object
 6   price                112650 non-null  float64
 7   freight_value        112650 non-null  float64
dtypes: float64(2), int64(2), object(4)
memory usage: 6.9+ MB
olist_order_items : None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   index                       32951 non-null  int64
 1   product_id                  32951 non-null  object
 2   product_category_name       32341 non-null  object
 3   product_name_lenght         32341 non-null  float64
 4   product_description_lenght  32341 non-null  float64
 5   product_photos_qty          32341 non-null  float64
 6   product_weight_g            32949 non-null  float64
 7   product_length_cm           32949 non-null  float64
 8   product_height_cm           32949 non-null  float64
 9   product_width_cm            32949 non-null  float64
dtypes: float64(7), int64(1), object(2)
memory usage: 2.5+ MB
olist_products_dataset : None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 681941 entries, 0 to 681940
Data columns (total 6 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   index                        681941 non-null  int64
 1   geolocation_zip_code_prefix  681941 non-null  int64
 2   geolocation_lat              681941 non-null  float64
 3   geolocation_lng              681941 non-null  float64
 4   geolocation_city             681941 non-null  object
 5   geolocation_state            681940 non-null  object
dtypes: float64(2), int64(2), object(2)
memory usage: 31.2+ MB
olist_geolocation : None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 3 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   index                          71 non-null     int64
 1   product_category_name          71 non-null     object
 2   product_category_name_english  71 non-null     object
dtypes: int64(1), object(2)
memory usage: 1.8+ KB
product_category_name_translation : None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 9 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   index                          99441 non-null  int64
 1   order_id                       99441 non-null  object
 2   customer_id                    99441 non-null  object
 3   order_status                   99441 non-null  object
 4   order_purchase_timestamp       99441 non-null  object
 5   order_approved_at              99281 non-null  object
 6   order_delivered_carrier_date   97658 non-null  object
 7   order_delivered_customer_date  96476 non-null  object
 8   order_estimated_delivery_date  99441 non-null  object
dtypes: int64(1), object(8)
memory usage: 6.8+ MB
olist_orders : None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 6 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   index                 103886 non-null  int64
 1   order_id              103886 non-null  object
 2   payment_sequential    103886 non-null  int64
 3   payment_type          103886 non-null  object
 4   payment_installments  103886 non-null  int64
 5   payment_value         103886 non-null  float64
dtypes: float64(1), int64(3), object(2)
memory usage: 4.8+ MB
olist_order_payments : None

In [5]:
all_dfs =[df_olist_customers,df_olist_sellers,df_olist_order_reviews,df_olist_order_items,df_olist_products,df_olist_geolocation,df_product_category_name_translation,df_olist_orders,df_olist_order_payments]
for df in all_dfs:
  for col in df:
    if 'timestamp'in col or 'date' in col:
      df[col]=pd.to_datetime(df[col])
      print(f"{col}: {df[col].dtype}")

review_creation_date: datetime64[ns]
review_answer_timestamp: datetime64[ns]
shipping_limit_date: datetime64[ns]
order_purchase_timestamp: datetime64[ns]
order_delivered_carrier_date: datetime64[ns]
order_delivered_customer_date: datetime64[ns]
order_estimated_delivery_date: datetime64[ns]

Query 1: Count and Percentage of Orders Purchased in Jan 2018 with 5 Review Score

# Write and execute a SQL query to count the number of orders purchased in January 2018 that have a review score of 5 and calculate the percentage of such orders.

In [23]:
import pandas as pd

query ='''SELECT COUNT(oo.customer_id) AS order_count FROM olist_orders oo
WHERE oo.order_purchase_timestamp >= '2018-01-01' AND oo.order_purchase_timestamp < '2018-02-01' AND
(SELECT r.review_score FROM olist_order_reviews r WHERE r.order_id = oo.order_id) = 5;'''
df_sql = pd.read_sql_query(query,con=engine)
df_sql.head()

   order_count
0         4071


 Query 2: Customer Purchase Trend Year-on-Year

Write and execute a SQL query to analyze the customer purchase trend year-on-year.

In [24]:
query='''SELECT strftime('%Y', oo.order_purchase_timestamp) AS year,
       COUNT(DISTINCT oo.customer_id) AS customer_count
FROM olist_orders oo
GROUP BY year
ORDER BY year;'''
df_sql = pd.read_sql_query(query,con=engine)
df_sql.head()

   year  customer_count
0  2016             329
1  2017           45101
2  2018           54011

5. Query 3: Average Order Values of Customers

Write and execute a SQL query to calculate the average order values of customers.

In [25]:
query ='''SELECT DISTINCT c.customer_unique_id, AVG(oi.price + oi.freight_value) AS avg_order_value
FROM olist_customers c
JOIN olist_orders o ON c.customer_id = o.customer_id
JOIN olist_order_items oi ON o.order_id = oi.order_id  GROUP BY c.customer_unique_id;'''
df_sql = pd.read_sql_query(query,con=engine)
df_sql.head()

                 customer_unique_id  avg_order_value
0  0000366f3b9a7992bf8c76cfdf3221e2           141.90
1  0000b849f77a49e4a4ce2b2a4ca5be3f            27.19
2  0000f46a3911fa3c0805444483337064            86.22
3  0000f6ccb0745a6a4b88665a16c9f078            43.62
4  0004aac84e0df4da2b147fca70cf8255           196.89

6. Query 4: Top 5 Cities with Highest Revenue from 2016 to 2018

Write and execute a SQL query to find the top 5 cities with the highest revenue from 2016 to 2018.

In [26]:
query='''SELECT c.customer_city, SUM(oi.price + oi.freight_value) AS total_revenue
FROM olist_customers c
JOIN olist_orders o ON c.customer_id = o.customer_id
JOIN olist_order_items oi ON o.order_id = oi.order_id
WHERE (SELECT strftime('%Y', o.order_purchase_timestamp) FROM olist_orders)
BETWEEN '2016' AND '2018' AND oi.order_item_id IS NOT NULL
GROUP BY c.customer_city
ORDER BY total_revenue DESC
LIMIT 5;'''
df_sql = pd.read_sql_query(query,con=engine)
df_sql

    customer_city  total_revenue
0       sao paulo     2170227.12
1  rio de janeiro     1154234.02
2  belo horizonte      416733.39
3        brasilia      352305.14
4        curitiba      244739.87

7. Query 5: State Wise Revenue Table Between 2016 to 2018

Write and execute a SQL query to create a state-wise revenue table between 2016 to 2018.

In [27]:
query='''SELECT c.customer_state, SUM(oi.price + oi.freight_value) AS total_revenue
FROM olist_customers c
JOIN olist_orders o ON c.customer_id = o.customer_id
JOIN olist_order_items oi ON o.order_id = oi.order_id
WHERE (SELECT strftime('%Y', o.order_purchase_timestamp) FROM olist_orders)
BETWEEN '2016' AND '2018' AND oi.order_item_id IS NOT NULL
GROUP BY c.customer_state;'''
df_sql =pd.read_sql(query,con=engine)
df_sql.head()

  customer_state  total_revenue
0             AC       19669.70
1             AL       96229.40
2             AM       27835.73
3             AP       16262.80
4             BA      611506.67

. Query 6: Top Successful Sellers in Terms of Goods Sold, Revenue, and Customer Count

Write and execute a SQL query to identify the top successful sellers in terms of the number of goods sold, total revenue, customer count, and sellers with the highest 5-star ratings.

In [28]:
query='''SELECT s.seller_id, COUNT(DISTINCT oi.order_id) AS goods_sold,
SUM(oi.price + oi.freight_value) AS total_revenue,
COUNT(DISTINCT o.customer_id) AS customer_count FROM olist_sellers s
 JOIN olist_order_items oi ON s.seller_id = oi.seller_id
 JOIN olist_orders o ON oi.order_id =o.order_id
WHERE(SELECT r.review_score FROM olist_order_reviews r WHERE r.order_id = oi.order_id) = 5
GROUP BY s.seller_id ORDER BY goods_sold DESC, total_revenue DESC, customer_count DESC LIMIT 5;'''
df_sql =pd.read_sql(query,con=engine)
df_sql.head()

                          seller_id  goods_sold  total_revenue  customer_count
0  cc419e0650a3c5ba77189a1882b7556a         989       73810.71             989
1  6560211a19b47992c3666cc44a7e94c0         945       74997.32             945
2  4a3ca9315b744ce9f8e9374361493884         862      109383.90             862
3  1f50f920176fa81dab994f9023523100         840       79584.52             840
4  da8622b14eb17ae2831f4ac5b9dab84a         770      101547.64             770

 Query 7: Delivery Success Rate Across States

Write and execute a SQL query to calculate the delivery success rate across different states.

In [29]:
query='''WITH deliveries AS (SELECT c.customer_state AS state,
COUNT(DISTINCT CASE WHEN o.order_status = 'delivered' THEN o.order_id END) AS delivered_orders,
COUNT(DISTINCT o.order_id) AS total_orders
FROM olist_customers c
JOIN olist_orders o ON c.customer_id = o.customer_id
JOIN olist_order_items oi ON o.order_id = oi.order_id GROUP BY c.customer_state)
SELECT state, delivered_orders, total_orders ,
(delivered_orders*100)/total_orders AS delevery_rate FROM deliveries;'''
df_sql =pd.read_sql(query,con=engine)
df_sql.head()

  state  delivered_orders  total_orders  delevery_rate
0    AC                80            81             98
1    AL               397           411             96
2    AM               145           147             98
3    AP                67            68             98
4    BA              3256          3358             96

10. Query 8: Preferred Form of Payment for Different Categories

Write and execute a SQL query to find the preferred form of payment for different product categories.

In [30]:
query='''SELECT p.product_category_name, op.payment_type, COUNT(op.payment_type) AS payment_count
FROM olist_products_dataset p
JOIN olist_order_items oi ON p.product_id = oi.product_id
JOIN olist_order_payments op ON oi.order_id = op.order_id
GROUP BY p.product_category_name, op.payment_type
ORDER BY p.product_category_name, payment_count DESC;'''
df_sql =pd.read_sql(query,con=engine)
df_sql.head()

       product_category_name payment_type  payment_count
0                       None  credit_card           1233
1                       None       boleto            318
2                       None      voucher            118
3                       None   debit_card             29
4  agro_industria_e_comercio  credit_card            145

11. Query 9: Distance Between Cities

Write and execute a SQL query to calculate the distance between cities.

In [31]:
query='''
WITH CityLocations AS (
  SELECT
    geolocation_city,
    AVG(geolocation_lat) AS avg_lat,
    AVG(geolocation_lng) AS avg_lng
  FROM
    olist_geolocation
  GROUP BY
    geolocation_city
)
SELECT
  cl1.geolocation_city AS city1,
  cl2.geolocation_city AS city2,
  (6371 * ACOS(
    COS(cl1.avg_lat * 3.141592653589793 / 180.0) * COS(cl2.avg_lat * 3.141592653589793 / 180.0) *
    COS(cl2.avg_lng * 3.141592653589793 / 180.0 - cl1.avg_lng * 3.141592653589793 / 180.0) +
    SIN(cl1.avg_lat * 3.141592653589793 / 180.0) * SIN(cl2.avg_lat * 3.141592653589793 / 180.0)
  )) AS distance_km
FROM
  CityLocations AS cl1
JOIN
  CityLocations AS cl2 ON cl1.geolocation_city < cl2.geolocation_city
WHERE
  cl1.geolocation_city IS NOT NULL AND cl2.geolocation_city IS NOT NULL
GROUP BY
  cl1.geolocation_city, cl2.geolocation_city
ORDER BY
  distance_km DESC
LIMIT 10;'''
df_sql =pd.read_sql(query,con=engine)
df_sql.head()

                city1                   city2  distance_km
0  ...arraial do cabo  santo antônio do canaã  8387.198025
1     arraial do cabo  santo antônio do canaã  8385.165688
2  armação dos búzios  santo antônio do canaã  8381.950088
3   armacao de buzios  santo antônio do canaã  8381.586118
4  armacao dos buzios  santo antônio do canaã  8381.556600